name: Build

on:
  push:
    branches: master
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Node
      uses: actions/setup-node@v1
      with:
       node-version: '12.x'

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install Server Extension Dependencies
      run: python -m pip install jupyterlab

    - name: Install Server Extension
      run: |
        set -eux
        pip install .
        jupyter serverextension enable --sys-prefix --py jupyter_videochat
        jupyter serverextension list

    - name: Validate Server Extension
      run: |
        set -eux
        jupyter serverextension list 1>serverextensions 2>&1
        cat serverextensions | grep "jupyter_videochat.*OK"

    - name: Install Lab Extension Build Dependencies
      run: |
        set -eux
        jlpm

    - name: Lint Lab Extension
      run: |
        jlpm run eslint:check

    - name: Build Lab Extension
      run: |
        jlpm build
        npm pack > tarball.txt

    - name: Install Lab Extension
      run: |
        jupyter labextension list
        jupyter labextension install --no-build --debug $(cat tarball)
        jupyter labextension list

    - name: Build Lab
      run: |
        jupyter lab build --debug --dev-build=False --minimize=True
        jupyter labextension list

    - name: Validate Lab Extension
      run: |
        jupyter labextension list 1>labextensions 2>&1
        cat labextensions | grep "jupyterlab-videochat.*OK"

    - name: Lab Browser check
      run: |
        python -m jupyterlab.browser_check
